---
galaxy_info:
  author: Your Name
  description: Simple ping connectivity test role
  company: Your Company
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - 8
        - 9
    - name: Fedora
      versions:
        - all

dependencies: []
