$ANSIBLE_VAULT;1.1;AES256
65366366663962333334653338346536353633383738623334616634393331616230356134336337
6264393835636131343563633733643030376261323334310a323737356463396465383662616638
37326237323639356236663734346265373962376632666232373966636362373738616437383361
3234393430643737330a653964313663316361373665623939383037613463393135306634663261
65353434633463363038393235656536663135363339646635643166333062336266326665303539
36383463316334333232353961333232623765383630353830623436626338383631333962623130
30383165623861353534343161626132316236323435353039303630333435323230633265313138
34316634336535626138313030643463623838303666336239656330343137636539313166346262
39663135303165306461313339313261303438396365303231633531616362303032623739666562
32326261373463386434633334633763353333303330353331303134326166306130653865343137
39333166316633313764333362663861393738356535396232383038663338393865313138383632
63363139356131396663373233613037656333326331653332306332626564633965643930353933
39386437616164633637303730663633343631313264353261643437656363343433363964326566
32396338353632633965383739386631333732383135666437396365326663343837313337616634
64656536303531396238643030666238353364373462303636633565363536303035666330313731
63373461383934623734336636666465613661653031306630636435613662343033636639313662
37313338643863666234643035653738653630636661333439663534356666386637336163616537
33663134643134643332643166396165386263313764353632663235376330636130363336323735
31383835613536646366383833373264663832323065353835656261353639653436363863313139
66393533333661343632613630393638303836663566376263353730613630383265376363653538
64353337326535393633613131356564313034646630313034656532643165333839
