---
galaxy_info:
  author: Your Name
  description: Collect and report system information (OS, IP, version, etc.)
  company: Your Company
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - 8
        - 9
        - 10
    - name: Fedora
      versions:
        - all

dependencies: []
